### ISSUE TITLE
Doesn't work with latest Vue 2.3.4

### ISSUE THREAD

**Issue by gtrbarbarian** [Microsoft/TypeScript-Vue-Starter#13]
First, I appreciate your work. 
However, an app starter is much less useful if I have to use your specific fork of vue and vue-router. I'm going to go out on a limb and say that most organizations are not going to want to be tied to another dev's fork, especially one that is customized. Is there a plan for a future build that will work with current builds of Vue? Otherwise, this is a non-solution for most folks.

**Comment by jimmykane** [comment]
Was excited about this project. Now I am not.

**Comment by ThePlastic** [comment]
I saw a pull request that accomplish exactly what you are looking for:
https://github.com/Microsoft/TypeScript-Vue-Starter/pull/5

**Comment by jimmykane** [comment]
Now I am again a bit excited.

**Comment by ThePlastic** [comment]
I particularly appreciated that pull-request because it adds the ability to use class-component and props-decorator. Any concept of using typecript's type-safe power with vue loses meaning if I can not leverage the type-check within components. Props-decorator and class-component solve that problem by allowing a more deep and profitable use of the typescript language

**Comment by DanielRosenwasser** [comment]
Everything should work out of the box with Vue 2.5+.
